### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by TianT1209** [Wapiti08/DeepLog#1]
Thanks for your contribution. But where your data comes from?

**Comment by Wapiti08** [comment]
Hi, thanks for your question. In fact, I am not quite sure about the specific link. But it is coming from a public dataset. 

Maybe it is from this [example](https://log-sharing.dreamhosters.com/). Please notice the timestamp. If you want to generate training dataset, you gotta splice the messages according to the right order on timestamp. 

If you want to collect it manually, you should check the logs at the location **/var/log/messages**

**Comment by TianT1209** [comment]
Ok. Thanks for your answer, I will try to use it.
