### ISSUE TITLE
parameter value vector file input

### ISSUE THREAD

**Issue by shoaib-intro** [Wapiti08/DeepLog#10]
Hi, 
Could you please close previous issue where I asked for `rmse`! 
I have found anomalies from execution path anomaly. when I select all parameters list for specific key to feed `parameter_value_vector` for detecting parameter anomalies I have faced many error so Just want to make sure about input to this file. 
When you select parameters using this
 ` data = df[df['EventTemplate']=='A <*> <*> was <*>']['ParameterList']` from structure log file which is parsed by LOGPAI parser it contains characters and numeric both values like below: 
![image](https://user-images.githubusercontent.com/56737996/165291277-01002d51-3043-44f4-80f4-b5fc8bc6a822.png)
To get numerical value I encoded and extracted only numeric values like below: 

![image](https://user-images.githubusercontent.com/56737996/165291802-f2236e47-6dee-4e01-b68a-fcec622306d9.png)

then I face error on line: 
`        # reshape 2D to 1D
        new_data[col_ord] = np.reshape(new_data[col_ord],new_data[col_ord].shape[0])`

**Could you please tell me how to correctly format input for parameter anomaly from structured log file (parsed by parser) directly for specific log key!
any piece of code for that if available!**

**Comment by Wapiti08** [comment]
I will give you a look in this weekend. By the way, I remember I encoded categorial data separately in the parameter vector. You can look at the code in this [part](https://github.com/Wapiti08/DeepLog/blob/master/Deeplog_demo/Execution_Path_Anomaly/log_value_vector.py). Remember there is a time gap for the first element in all the vectors.

**Comment by shoaib-intro** [comment]
I already checked this `log_value_vector` file thoroughly but didn't found encoding into it however you've done encoding as feature engineering in `parameter_value_vector` but this is where I am unable to proceed. 
I would appreciate your time if you find time to have a look!

**Comment by shoaib-intro** [comment]
Hi
Is this fine to have a review tomorrow evening if you're available!

**Comment by shoaib-intro** [comment]
Hi,
Could you please have a look into [my_repo](https://github.com/shoaib-intro/logs_Analysis/tree/main/test) for parameter anomaly detection model.
I have `trace_df`, `model.h5`, and `log_structured.pkl` containes normal parameter while `param_anomaly_log_structured.pkl` contains anomalous parameters.
I just want to run this file by second model and curious what should be the input format at following line: 

![image](https://user-images.githubusercontent.com/56737996/166108383-767cc9dc-2418-41c7-8643-e49a49291a8e.png)

where is encoding for this parameter execution file? could you please try this file as or have a look at my machine!

I tried encoding way which you've used in `Demo parameter` anomaly file but again its not working.

**Comment by shoaib-intro** [comment]
Please correct me if I am wrong!
- I encoded parameters for each log key in matrix form as following:

![image](https://user-images.githubusercontent.com/56737996/166112017-1cf64e70-27eb-449b-80a3-abae0e087dab.png)

- Now I don't need feature engineering part which you've done in `Parameter_Value_Vector.py` and directly switched to transpose of this matrix and splitted with 5 steps window size: 

![image](https://user-images.githubusercontent.com/56737996/166112200-f61b5edb-1347-49c7-bea8-a1db962de545.png)

- when I trained model and tested RME are high and results are like below (**are these result correct?**): 

![image](https://user-images.githubusercontent.com/56737996/166112276-1ab12cec-be2c-4caa-9d31-b85828d0afd9.png)
 

- Last important question: 
When I train looked into `trace_df` file there are different log keys marked as `para_pred` anomaly while I am wondering I trained it only on `Event key 35` but it predicted for all others as well how?

**Comment by Wapiti08** [comment]
Yeah, you are right on that part if without a normalization process. 

For your last question,
There is a process to looking back, you have to make a record for all the original indexes after you extract the vectors for one log key. After you train and predict, you have to make sure of that indexes to find original position and mark the anomaly logs.
