### ISSUE TITLE
trace para_pred for all log key parameters

### ISSUE THREAD

**Issue by shoaib-intro** [Wapiti08/DeepLog#11]
Hi, 
In online learning I am not able to incorporate feedback ? any idea?

**Comment by Wapiti08** [comment]
You can take a look at this [gist](https://gist.github.com/Wapiti08/9b515feaeefda263cbc880db7ead4053). I will try to catch you up this week. I am quite busy recently.

**Comment by shoaib-intro** [comment]
> You can take a look at this [gist](https://gist.github.com/Wapiti08/9b515feaeefda263cbc880db7ead4053). I will try to catch you up this week. I am quite busy recently.

I already got this from your repo which is similar to this but I have prepared three notebooks once if you can review this I am waiting since last week but ended with hopeless. I have few queries to ask you once you're available.
- `Pre-processing` into `log_value_vectors`
-  `Excution path` output `trace_df`
-  `Parameter Execution` output `trace_df_param`
so please tell when are you available. and what to prepare more to take your short call.

**Comment by Wapiti08** [comment]
We can discuss it this weekend, I will give it a look before.

**Comment by shoaib-intro** [comment]
Alright, thanks, 
mostly I solved prediction with first Model while currently feedback is running to check result I need mainly your intention on second model where taking all `log key` parameters and finding anomalies parameter based, like you've shown in `trace_df` file. 
I have prepared three notebooks and will upload on my repo to find work on each step separately. 
thanks!
humbly request please be available for even short time but we need to solve second model.

**Comment by shoaib-intro** [comment]
Hey wapiti, 
I successfully implemented logkey execution part where i would be able to mark anomalies against each POD but with pytroch I will share you later once optimize it.
While for second model I embedded parameters to generate matrix then trained each logkey (i  my case I have 406logkeys) as dataset is big. could you please share code how to mark parameters anomalies once we trained it.!

**Comment by Wapiti08** [comment]
Please check the file **Parameter_Value_Vector/Parameter_Value_Vector.py**

The **anomaly_match** function is to match the anomaly logs. The **visual_mses** function is to visual the anomaly error with a baseline making the threshold.

**Comment by shoaib-intro** [comment]
I tried once this code for parameter anomaly detection but it ran into different errors, tried to fix it but few were unable to solve. In this file, you're cleaning one logkey data as first step and then applying Bi-directional LSTM while at same time you are checking anomalies which is not correct in real case. Do we need to store rmses/mses values to identify it on live test data?
