### ISSUE TITLE
Model Performance Questions

### ISSUE THREAD

**Issue by shoaib-intro** [Wapiti08/DeepLog#12]
Hi @Wapiti08 ,

I trained `First model` on my data set of 1M log line with 2% loss and 47% accuracy over. When I test over rest of 4M logline with `0.1` probability it gives me 30% of whole data as anomalies. how to reduce this? 
On way I tried to train it with probability `0.5` there is no effect on model and similar anomalies are detected. Could you please suggest what is reason why model is not fitting on data or how to increase it better learning.

**Comment by Wapiti08** [comment]
Hi,

Sorry for the late reply.

- For the accuracy, has you used the normalization? Is that code on your resp? May I can have a check this week.

- Can you please specify what the probability means? and where it plays a role?
