### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by anissa404** [Wapiti08/DeepLog#2]
Hi Wapiti08, 

wow, you have done some great work here! Thank you! 
But I have some questions. I'm trying to use unsupervised Learning for anomlay detection. Do I have to train the model first with data which is clear of anomalies. And then put malicious logs in the second phase? Or can I input collected logs where I do not know if there is anomaly or not into the model?

**Comment by Wapiti08** [comment]
Hi Anissa,

Thanks for your question. To be honest, even you put definite malicious logs for the input, you may not be able to find the specific one. It is totally depending on what you input for your training data. The evaluation is to check the substantial deviations between your training and testing data. There is still a lot of space to improve, especially for improvement during the testing to check the real and predicted values (false positive mostly). 
I would recommend you to train with normal behaviors (in your view) first, then put the malicious as the testing data. Check the result and improve the accuracy. The project is just a basic one to give you some ideas for the complete Deeplog. 
Hope I answered your question.

**Comment by Wapiti08** [comment]
Hi Anissa,

Thanks for your question. To be honest, even you put definite malicious logs for the input, you may not be able to find the specific one. It is totally depending on what you input for your training data. The evaluation is to check the substantial deviations between your training and testing data. There is still a lot of space to improve, especially for improvement during the testing to check the real and predicted values (false positive mostly). 
I would recommend you to train with normal behaviors (in your view) first, then put the malicious as the testing data. Check the result and improve the accuracy. The project is just a basic one to give you some ideas for the complete Deeplog. 
Hope I answered your question.

**Comment by anissa404** [comment]
Hello Wapiti08, 

thanks, I appreciate your fast reply!! Yes, your answer helped me a lot. So when I train with normal behavior and then apply the trained model on new data,  it will be a kind of semi-supervised learning?

Many thanks in advance :)

**Comment by Wapiti08** [comment]
In my opinion. it is not semi-supervised learning. The official definition is: **combines a small amount of labeled data with a large amount of unlabeled data during training**.

To be honest, it can be treated as supervised learning (not that accurate from the definition). But it is definitely not unsupervised learning, cuz there is not clustering process during it. For the RNN and training on the time-series data, it is the problem that can not simply be defined as supervised or unsupervised. I would recommend you to understand this problem based on the principles. You know an execution path is right or without a problem, the label is implicitly beign. Otherwise it is an anomaly.

**Comment by anissa404** [comment]
Hi Wapiti08, 
thank you for your explanation of semi-supervised learning. I think I will focus again on unuspervised learning.

I'm working on anomlay detection for my own syslogs (Linux system logs) with 80 000 lines. I was really happy finding your account here, beacause you already implemented the feature extraction with sliding windows for Linux logs :D  For 'training' I used principal component analysis and the output was no anomalies for any sequence. Since the data were my own syslogs of normal bevior, this was to be expected. 

**But now I don't know how to 'test' the model.** I manipulated some loglines, parsed the file, generated a logmatrix and trained a new model, but still the algorithm shows me no anomaly sequences.  My next consideration was to train a model again with the normal logs and to put a manipulated set into the testphase in the demo-file. But here I don't understand how it should work: the manipulated set goes separate to the normal dataset into logparsing, but so the calculated events on the structured logfiles won't be the same and the Logmatrix is generated on an other base. I hope you understand what I mean :S 

For the Linux example dataset with 2000 lines I got from the Logpai platform, the model finds anomaly sequences. But here is my problem, that I can not validate it. 

Sorry for my long text, but I hope you have an advice and/or explanation for me :)

**Comment by Wapiti08** [comment]
Yeah. Thanks for your question. In my project, there are two separate model sets (Deeplog For DL and PCA for ML). I considered your concern before. As I remember, I add an updating or appending mechanism to the events. It will help to make sure there is not repetition for the event path. (event ---> numeric presenting)
You can compute together or separately for the training and testing dataset. There should be no difference. I have to say I am not sure whether the PCA can detect the anomaly logs. I really can not guarantee that. If you understand the principles behind that algorithm, you will know it would be more efficient to detect the outlier based on dimension projection. It is hard to explain. I used to test it with two totally different datasets (but from the same source). I got the result with anomaly logs. But I have no idea how to explain it easily. The Deeplog would be more helpful from this aspect. 
I would recommend you to read the reference paper for this method and see how to explain the anomly. I did not remember too much. Hope that can help you. Thanks.

**Comment by Wapiti08** [comment]
By the way, I want to mention you can set proper intervals to split the timelines. It really depends on the density of your timestamps. Just try to get enough split results for lines in the array. It would be helpful for the model to learn more features.

**Comment by Wapiti08** [comment]
> 
> 
> Hi Wapiti08,
> thank you for your explanation of semi-supervised learning. I think I will focus again on unuspervised learning.
> 
> I'm working on anomlay detection for my own syslogs (Linux system logs) with 80 000 lines. I was really happy finding your account here, beacause you already implemented the feature extraction with sliding windows for Linux logs :D For 'training' I used principal component analysis and the output was no anomalies for any sequence. Since the data were my own syslogs of normal bevior, this was to be expected.
> 
> **But now I don't know how to 'test' the model.** I manipulated some loglines, parsed the file, generated a logmatrix and trained a new model, but still the algorithm shows me no anomaly sequences. My next consideration was to train a model again with the normal logs and to put a manipulated set into the testphase in the demo-file. But here I don't understand how it should work: the manipulated set goes separate to the normal dataset into logparsing, but so the calculated events on the structured logfiles won't be the same and the Logmatrix is generated on an other base. I hope you understand what I mean :S
> 
> For the Linux example dataset with 2000 lines I got from the Logpai platform, the model finds anomaly sequences. But here is my problem, that I can not validate it.
> 
> Sorry for my long text, but I hope you have an advice and/or explanation for me :)

Hi mate, I just got confirmed. The anomaly detection based on time series data is unsupervised learning from authorities.
