### ISSUE TITLE
Workflow part missing

### ISSUE THREAD

**Issue by shoaib-intro** [Wapiti08/DeepLog#4]
Hi,
I readout Deeplog paper is one of the best research have been done.
I am trying this in my research work as pre-task and looking for source code but unable to find source code which includes three models features:

1. `logKey` based prediction of next key (= log key path stacked LSTM based prediction)
2. `log Parameter` based prediction of next parameter (= log parameters LSTM based prediction)
3. `Workflow` clustering based creation.

I have looked around different repos with name '`deeplog`' and wasted a long time on learning repos but nowhere found complete three models implementation. I looked into following repos:
```
https://github.com/donglee-afar/logdeep
https://github.com/Wapiti08/DeepLog
https://github.com/wuyifan18/DeepLog
https://github.com/nailo2c/deeplog
https://github.com/PragyaShukla2580/DeepLog
```

could you please provide any source for **_Workflow_** and **_parameter anomaly with Deeplog approach_** not PCA to get done as part of pre-work in my research. 

email: m.shoaib_ali@outlook.com

Best Regards,

**Comment by Wapiti08** [comment]
That workflow part is kind of the process to update model based on prediction result. To be more precise, it is online learning. 
I have made a separate part from that on the [Online Learning](https://gist.github.com/Wapiti08/9b515feaeefda263cbc880db7ead4053).

For secret reason, I am not able to tell you all. But hopefully you can get some ideas from that gist.

For this parameter anomaly with Deeplog approach, I have included in that project. Please check [this](https://github.com/Wapiti08/DeepLog/blob/master/Parameter_Value_Vector/Parameter_Value_Vector.py)

**Comment by shoaib-intro** [comment]
thanks for your quick response!
I mean by workflow is **clustering based creating workflows** mentioned in Deeplog paper: [Deeplog workflow second model](https://www.cs.utah.edu/~lifeifei/papers/deeplog.pdf )

I just started working on your repo before starting wanted to make sure is everything implemented according to [Deeplog](https://www.cs.utah.edu/~lifeifei/papers/deeplog.pdf ) paper especially Workflow model in this paper useful for me to find root cause of problem. 

Could you please share your LinkedIn or social profile to get in touch!

**Comment by Wapiti08** [comment]
Oh, I found it out. Sadly I did not implement that part in my resp. Maybe you need to find other projects.

**Comment by Wapiti08** [comment]
You can reopen it if you have any other problems.
