### ISSUE TITLE
What is order of files in Parameters_Value_Vector

### ISSUE THREAD

**Issue by shoaib-intro** [Wapiti08/DeepLog#5]
Hi @Wapiti08 

Thanks for your `parameters based anomaly` detection model! in this folder there are many files and I always get confused, what is order of files execution if I take `structured logs file` from parser, I sorted according to below order is this correct? 

1. transform_numerical_data - `all data into numerical for LSTM`
2. Parameter_Value_Vector -  `hstack, standardization`
3. Visualize_value_vector - `see how parameters value vectors are`
4. gen_log_key_matrix - `generate the matrix for every log key: why this matrix needed?`
5. anomaly_predict - `predicts anomaly based on given thresholds`
6. matrix_analyse_report_anomaly - ` analyse the log key matrix and report the anomaly logs`

what is input to this model? is this `parameters column` from structured log file from parser? 

Best Regards

**Comment by Wapiti08** [comment]
Totally, this is just part of the core modules. I added some experiments to this folder as well. You just need to refer to Parameter_Value_Vector.py file to grab ideas. But you can also get some rough basic ideas from other separate files. 

Answering your questions, you need to generate a structured csv by logparser , then you need to do some stuff to generate dataframe with parameter column in it. The input is the parameter column inside your new generated framework (csv). To see the full cycle, you can check the log_value_vector_gen inside [Execution](https://github.com/Wapiti08/DeepLog/blob/master/Deeplog_demo/Execution_Path_Anomaly/Execution_Path_Anomaly.py)

**Comment by shoaib-intro** [comment]
Thanks your explanation 
- What are `batch_variables_path` ? why are used here and which files creates these variable?

- When I execute this code step by step I don't find `callback`  Where is it define?
` callbacks = Mycallback()`
- Which files creates these dictionaries
`dict_filename_com = 'path_key_name_dict_com.pkl'`
could you please explain!

**Comment by Wapiti08** [comment]
- To be honest, I have forgotten the answers to your first question and three questions. I would recommend you implement by the context in the paper. If you met problems, you could refer to this resp. 
- The second question you can easily use:

```
tf.keras.callbacks.EarlyStopping(patience=2)
```
