### ISSUE TITLE
The code isn't working

### ISSUE THREAD

**Issue by heyd7fc** [Wapiti08/DeepLog#6]
Your Code is not working. May I ask you to modify your code?

It's Deeplog Executionexecution. What is callback inDeeplog_demo/Execution_Path_Anomaly/Execution_Path_Anomaly.py?
![image](https://user-images.githubusercontent.com/102908398/163202763-83834036-4857-47c8-b04d-3a80cb9f56e4.png)

I tried to change it and set the correct class, but there was a mistake:
ValueError: Error when checking input: expected dense_1_input to have 2 dimensions, but got array with shape (8929, 5, 1)

Other than that, /Execution_Path/Execution_Path_Anomaly.py doesn't work

**Comment by Wapiti08** [comment]
Hi,

Thanks for reaching out. I am really sorry for your problem. It is quite a mass for the code in the demo. I gave a quick fix. I hope it can work now.

As for the second part, I just gave the core code. The data was not provided for sensitive reasons. If you want to play, you can provide your own dataset. The code in the top Execution_Path and Parameter_Value_Vector folder is more official and updated.

**Comment by heyd7fc** [comment]
1. The project is still not working and I'm trying to fix it, but there are a number of problems. 
    I Can't fix it. Can I ask you to make a complete change to the code?

![image](https://user-images.githubusercontent.com/102908398/163541021-f1f63d5b-70bf-4d30-943c-91adf1bf85c2.png)



3. Why is your Y_train still a string type and not a number?
  File "Execution_Path_Anomaly.py", line 475, in test
    model = lstm_model(x_train, y_train)    
  ValueError: could not convert string to float: 'opened'


Thank you for your help
