### ISSUE TITLE
how rmses are being plot in parameter Anomaly detection

### ISSUE THREAD

**Issue by shoaib-intro** [Wapiti08/DeepLog#8]
I see most of my parameter matrices are showing anomalies because 'rmses' are same in this case as you appended to form list:
step1: I padded as I have different length parameter digits  like this
![padded](https://user-images.githubusercontent.com/56737996/164288816-bec354c4-d021-4397-9e56-9ba5bfce5b25.jpg)

step 2: 
how to detect anomaly as in my case all log keys rmse are added up and not clear how you're choosing threshold is thius based on all rmse of all file or individual file?  

![rmse](https://user-images.githubusercontent.com/56737996/164289267-155565e8-fd0e-4a2c-a60f-220632d502e3.jpg)

Could you please explain as after few logkeys most are showing anomalies.

**Comment by Wapiti08** [comment]
Hi Ali,

For your first question, I need more details on that. 

For your sec question, if you do not mind, I can contribute to your project, which is easier for me. I chose the threshold based on the value the paper mentioned. 

For the rmse calculation:
- I use rmse based on the paper only, for which that is a question regarding prediciton while not classification. So the rmse the most common way to measure that. It will basically measure the error between predicted and true values. If the error is too large, it means it would be a potential anomaly prediction.
- In the parameter_value_vector, you have to extract the rows within the **same log key**
- After you get the values within the same log key, for example, three element in every row [1, 'test', 'false'] for log key 2, you need to convert the string to numeric data with labelencoder or similar encoding methods. 
- predict and then calculate the rmse, the **rmse** is based on different groups of log keys. which is not for all files (all log keys).
- The anomaly detection here is based on every log key group.

I am not sure whether I answered your questions. Let me know if you have further questions.

**Comment by shoaib-intro** [comment]
Hi,
Thanks for detailed response! I worked on Demo folder but checked now `parameter_value_vector` file it contains test for single logkey. by contribution you mean on GitHub repo? 
Let me sort out my file I will come to you.. are you available tomorrow to reply here?

**Comment by shoaib-intro** [comment]
Hi, Could you please tell me what `trace_df` file contains inside.
I checked in code its numeric logkey values. is this unique log key id's? Which python file generates this `trace_df` ?
![trace](https://user-images.githubusercontent.com/56737996/164969327-71c37234-a594-4d1c-ba00-03e24403b15c.jpg)

**Comment by Wapiti08** [comment]
Yes, you are right. I did not think I add this script to generate the trace_df file. But I can tell you it is composed of the unique id (the id of log) and numeric log key (labelencoded).

**Comment by shoaib-intro** [comment]
Log parser returns hexadecimal values like `Event_id = e32ac2` but in your trace file we need `int` ids
What about if I hash record id based on log message? 
When I hashed these values contains negative as well. will it work?
![p](https://user-images.githubusercontent.com/56737996/164971059-7ce8796e-ba6e-49bd-ad8a-570a6e6d7fc4.jpg)

**Comment by Wapiti08** [comment]
I think there is a difference in the raw data. I am not sure whether you know about logstash. There is a unique id for every single log. In this project, the record id means that id. I am not sure about your unique id.

**Comment by Wapiti08** [comment]
I encode the log key with labelencoder, I refer to the logparer to generate parameter value vector only

**Comment by shoaib-intro** [comment]
BTW why we need to encode logkey? I saw in `Parameter_Value_Vector` you're encoding only parameters. while in your `trace_df.csv ` there is Logkey as log parser returns. its not encoded. so its confusing at this point.
Secondly if I share you logs data with normal and abnormal file will you contribute it on my private repo?

**Comment by Wapiti08** [comment]
- There are two main detection models inside Deeplog, the first one is the execution path, which is on the log key. But in order to train that data, the log key should be converted into a numeric array.
- I will contribute to that if you share with me

**Comment by shoaib-intro** [comment]
Hi, I have added you as contributor could you please tell me when you're done!
Please it s requested upload files in order so I can run in same way to find anomalies!
I spend long time on your repo but Demo and other folder are bit confusing relation both are little bit different.
